[package]
name = "m-core"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
thiserror.workspace = true
tracing.workspace = true
serde.workspace = true
toml.workspace = true
config.workspace = true
